# Generated by Django 3.0.11 on 2021-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
