# Generated by Django 3.0.11 on 2021-04-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210415_2122'),
        ('students', '0002_auto_20210123_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmessages',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Student Messages'},
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='teachers_comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmessages',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='class_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Class'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='remark',
            field=models.CharField(max_length=20),
        ),
    ]
