# Generated by Django 3.0.11 on 2021-04-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210415_2122'),
        ('students', '0003_auto_20210415_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='sub_class',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.SubClass'),
        ),
    ]
