# Generated by Django 3.0.11 on 2020-12-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_session'),
        ('students', '0004_subject_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.Session'),
        ),
    ]
