# Generated by Django 3.0.11 on 2021-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_subjectresult_head_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
