# Generated by Django 3.0.11 on 2021-05-19 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20210518_2221'),
        ('students', '0006_studentmodel_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='studentsfile/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='sub_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.SubClass'),
        ),
    ]
