# Generated by Django 3.0.11 on 2020-12-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_teachermodel_sub_class'),
        ('students', '0006_subjectresult_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='sub_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.SubClass'),
        ),
    ]
