# Generated by Django 3.0.11 on 2020-12-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_teachermodel_sub_class'),
        ('students', '0008_studentmodel_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.StudentModel')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.TeacherModel')),
            ],
        ),
    ]
