# Generated by Django 3.0.11 on 2021-06-03 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
