# Generated by Django 3.0.11 on 2021-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmessages',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='studentmessages',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
