# Generated by Django 3.0.11 on 2021-01-21 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_auto_20210121_0428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0010_auto_20210105_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Class'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='sub_class',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.SubClass'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='session',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Session'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Subject'),
        ),
    ]
