# Generated by Django 3.0.11 on 2021-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20210602_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
