# Generated by Django 3.0.11 on 2021-01-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_class_section'),
        ('students', '0011_auto_20210121_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Section'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Section'),
        ),
        migrations.AlterField(
            model_name='studentmessages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
