# Generated by Django 3.0.11 on 2021-06-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_code_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
