# Generated by Django 3.0.11 on 2021-06-10 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20210518_2223'),
        ('students', '0012_subjectresult_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.Section'),
        ),
    ]
