# Generated by Django 3.0.11 on 2021-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_code_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
