# Generated by Django 3.0.11 on 2021-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20211001_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classworkpost',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='classworkpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='textpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
