# Generated by Django 3.0.11 on 2021-10-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20211009_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpost',
            name='slug',
        ),
    ]
