# Generated by Django 3.0.11 on 2021-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_textpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
