# Generated by Django 3.0.11 on 2021-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210122_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
