# Generated by Django 3.0.11 on 2020-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
