# Generated by Django 3.0.11 on 2021-01-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210123_1116'),
        ('teachers', '0003_auto_20210123_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.AdminModel')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.TeacherModel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
