# Generated by Django 3.0.11 on 2021-01-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210123_1116'),
        ('teachers', '0004_teachermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermessages',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdminModel'),
        ),
        migrations.AlterField(
            model_name='teachermessages',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.TeacherModel'),
        ),
    ]
