# Generated by Django 3.0.11 on 2021-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20210126_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='address',
            field=models.TextField(default='clouds'),
        ),
    ]
