# Generated by Django 3.0.11 on 2021-04-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teachermodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Subclasses'},
        ),
        migrations.AlterModelOptions(
            name='teachermessages',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Teacher Messages'},
        ),
    ]
