# Generated by Django 3.0.11 on 2021-05-19 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210415_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.CharField(blank=True, default='change@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='mobile',
            field=models.CharField(blank=True, default='sharks', max_length=11),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacherfile/'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='sub_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.SubClass'),
        ),
    ]
