# Generated by Django 3.0.11 on 2021-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20210518_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
