# Generated by Django 3.0.11 on 2021-09-29 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20210518_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
