# Generated by Django 3.0.11 on 2020-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20201204_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='static/landing/team/01.jpg', upload_to='teacherfile'),
        ),
    ]
