# Generated by Django 3.0.11 on 2020-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_auto_20201204_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teacherfile'),
        ),
    ]
