# Generated by Django 3.0.11 on 2020-12-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20201204_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
