# Generated by Django 3.0.11 on 2020-12-07 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201207_0847'),
        ('teachers', '0013_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='wannabe', max_length=150, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='teacherfile/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
            ],
            options={
                'ordering': ['joining_date', 'name'],
            },
        ),
    ]
