# Generated by Django 3.0.11 on 2020-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
