# Generated by Django 3.0.11 on 2020-12-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_class', models.CharField(max_length=50)),
                ('class_name', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
