# Generated by Django 3.0.11 on 2020-12-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_auto_20201219_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='sub_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.SubClass'),
        ),
    ]
