# Generated by Django 3.0.11 on 2021-01-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_teachermodel_sub_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Class'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='sub_class',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.SubClass'),
        ),
    ]
