# Generated by Django 3.0.11 on 2021-01-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_auto_20210122_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.Section'),
        ),
    ]
