# Generated by Django 3.0.11 on 2021-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
