# Generated by Django 3.0.11 on 2020-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teach',
            field=models.BooleanField(default=False),
        ),
    ]
