# Generated by Django 3.0.11 on 2020-11-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_teach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teach',
            new_name='is_student',
        ),
    ]
