# Generated by Django 3.0.11 on 2020-12-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201203_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
