# Generated by Django 3.0.11 on 2021-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210518_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='adminfile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
