# Generated by Django 3.0.11 on 2021-09-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210621_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_email', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdminModel')),
            ],
            options={
                'verbose_name_plural': 'Admin Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
