# Generated by Django 3.0.11 on 2020-12-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentmore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_admins',
        ),
    ]
