# Generated by Django 3.0.11 on 2021-10-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('allotted_storage_space', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upcoming_price_per_month', models.FloatField(blank=True, null=True)),
                ('upcoming_price_per_year', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('college_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone_no', models.CharField(max_length=13)),
                ('card_info', models.CharField(max_length=16)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('used_storage_space', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_active', models.BooleanField(default=True)),
                ('plan_cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('plan_subscribed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Plan')),
            ],
        ),
    ]
