# Generated by Django 3.0.11 on 2020-12-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201204_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMore',
        ),
    ]
