# Generated by Django 3.0.11 on 2020-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201204_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Teacher', 'TEACHER'), ('Student', 'STUDENT')], default='Student', max_length=50, verbose_name='Type'),
        ),
    ]
