# Generated by Django 3.0.11 on 2020-12-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_delete_teacher'),
        ('users', '0012_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='TeacherModel',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
