# Generated by Django 3.0.11 on 2020-12-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_delete_teacher'),
        ('users', '0013_auto_20201205_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'ordering': ['joining_date', 'name']},
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(default='wannabe', max_length=150, verbose_name='Full Name'),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='studentsfile/')),
                ('fathers_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mothers_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.TextField()),
                ('emergency_mobile_number', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Class')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
