# Generated by Django 3.0.11 on 2020-12-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201205_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
