# Generated by Django 3.0.11 on 2020-12-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201207_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admins',
            new_name='is_admin',
        ),
    ]
