# Generated by Django 3.0.11 on 2021-01-22 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_class_section'),
        ('users', '0016_auto_20201209_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='adminfile/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Section')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
